name: legis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - lxml
  - pandas
  - seaborn
  - matplotlib
  - pip
  - pytorch
  - sentencepiece 
  - ipykernel
  - pip:
      - transformers